### ISSUE TITLE
New Bug Report

### ISSUE THREAD

**Issue by HuhMe9** [Pure-L0G1C/Instagram#37] opened 2018-06-01 11:03 UTC
C:\Users\HP\Desktop\instagram-bruter>python instagram.py -h
Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    from lib.bruter import Bruter
  File "C:\Users\HP\Desktop\instagram-bruter\lib\bruter.py", line 5, in <module>
    from .spyder import Spyder
  File "C:\Users\HP\Desktop\instagram-bruter\lib\spyder.py", line 5, in <module>
    from requests import Session
ModuleNotFoundError: No module named 'requests'

**Comment by Pure-L0G1C** [comment] 2018-06-01 12:49
It is not a bug, you need to install requests before you can run the
program. pip install -U requests

**Comment by m-henderson** [comment] 2018-06-01 22:30
@HuhMe9 did that solve your issue? If so, I am going to go ahead and close this issue.

**Closed** 2018-07-11 21:42 UTC
